spring.application.name=demo

server.port=8085

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/poprc
spring.datasource.username=postgres
spring.datasource.password=paulo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Zoho Authentication
zoho.auth.client-id=1000.KP3NMGY9KZ2O0DWYOEOH437HFNDHXC
zoho.auth.client-secret=5ce791d1b5040f1085528fbd50ce657832e00a45e9
zoho.auth.redirect-uri=http://localhost:8085/callback
zoho.auth.auth-url=https://accounts.zoho.com/oauth/v2/auth
zoho.auth.token-url=https://accounts.zoho.com/oauth/v2/token
zoho.auth.scope=ZohoCRM.modules.ALL
zoho.auth.account-id=926119382

# Spring Security OAuth2 Client Configuration
spring.security.oauth2.client.registration.zoho.client-id=1000.KP3NMGY9KZ2O0DWYOEOH437HFNDHXC
spring.security.oauth2.client.registration.zoho.client-secret=5ce791d1b5040f1085528fbd50ce657832e00a45e9
spring.security.oauth2.client.registration.zoho.client-name=Zoho
spring.security.oauth2.client.registration.zoho.scope=ZohoCRM.modules.ALL
spring.security.oauth2.client.registration.zoho.redirect-uri=http://localhost:8085/login/oauth2/code/zoho
spring.security.oauth2.client.registration.zoho.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.zoho.client-authentication-method=client_secret_post

# Spring Security OAuth2 Provider Configuration
spring.security.oauth2.client.provider.zoho.authorization-uri=https://accounts.zoho.com/oauth/v2/auth
spring.security.oauth2.client.provider.zoho.token-uri=https://accounts.zoho.com/oauth/v2/token
spring.security.oauth2.client.provider.zoho.user-info-uri=https://www.zohoapis.com/crm/v2/users?type=CurrentUser
spring.security.oauth2.client.provider.zoho.user-name-attribute=id
