package com.poprc.demo.model;

public enum StatusOS {
    ABERTA,
    AGUARDANDO_VISTORIA,
    AGUARDANDO_RETIRADA,
    EM_EXECUCAO,
    AGUARDANDO_VALIDACAO,
    AGUARDANDO_DEVOLUCAO,
    AGUARDANDO_AUDITORIA,
    AGUARDANDO_ENCERRAMENTO,
    CONCLUIDA,
    FATURADA
}
