CREATE TABLE IF NOT EXISTS projetos_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id BIGINT NOT NULL REFERENCES projetos(id),
    funcionario_id BIGINT NOT NULL REFERENCES funcionarios(id),
    papel VARCHAR(40) NOT NULL,
    responsavel_principal BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_projeto_membro_funcionario UNIQUE (projeto_id, funcionario_id)
);

CREATE INDEX IF NOT EXISTS idx_projetos_membros_funcionario
    ON projetos_membros(funcionario_id);

INSERT INTO projetos_membros (projeto_id, funcionario_id, papel, responsavel_principal)
SELECT p.id, p.responsavel_id, 'RESPONSAVEL_TECNICO', TRUE
FROM projetos p
WHERE p.responsavel_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM projetos_membros pm
      WHERE pm.projeto_id = p.id AND pm.funcionario_id = p.responsavel_id
  );
