--
-- PostgreSQL database dump
--

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: as_builts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.as_builts (
    id bigint NOT NULL,
    historico_versoes text,
    nome_arquivo character varying(255) NOT NULL,
    tipo_arquivo character varying(255) NOT NULL,
    url_arquivo character varying(255) NOT NULL,
    versao integer NOT NULL,
    projeto_id bigint NOT NULL
);


--
-- Name: as_builts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.as_builts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.as_builts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: atividade_comarca_fotos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.atividade_comarca_fotos (
    atividade_comarca_id bigint NOT NULL,
    url_foto text
);


--
-- Name: atividades_comarca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.atividades_comarca (
    id bigint NOT NULL,
    data_encerramento date,
    data_inicio date NOT NULL,
    data_registro timestamp(6) without time zone,
    descricao_atividades text NOT NULL,
    comarca_id bigint NOT NULL
);


--
-- Name: atividades_comarca_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.atividades_comarca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.atividades_comarca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: atividades_padrao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.atividades_padrao (
    id bigint NOT NULL,
    ativo boolean,
    categoria character varying(255),
    criado_em timestamp(6) without time zone,
    nome character varying(255) NOT NULL,
    ordem_exibicao integer
);


--
-- Name: atividades_padrao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.atividades_padrao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.atividades_padrao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comarca_materiais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comarca_materiais (
    id bigint NOT NULL,
    nome_material character varying(255),
    quantidade_auditada numeric(14,3) NOT NULL,
    quantidade_prevista numeric(14,3) NOT NULL,
    comarca_id bigint,
    estoque_baixado boolean,
    material_id bigint,
    estoque_reservado boolean,
    data_hora_retirada timestamp(6) without time zone,
    data_hora_solicitacao timestamp(6) without time zone,
    data_hora_uso timestamp(6) without time zone,
    descricao_faltante text,
    item_adicional boolean,
    material_faltante boolean
);


--
-- Name: comarca_materiais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comarca_materiais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comarca_materiais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comarcas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comarcas (
    id bigint NOT NULL,
    contato_local character varying(255),
    endereco character varying(255),
    juiz_responsavel character varying(255),
    nome_comarca character varying(255) NOT NULL,
    pendencias text,
    percentual_concluido numeric(19,2),
    quantidade_pontos integer,
    situacao character varying(255),
    projeto_id bigint,
    assinatura_base64 text,
    foto_vistoria_url character varying(255),
    ordem_servico_id bigint,
    etapa_atual integer DEFAULT 1,
    as_built_status character varying(255),
    descricao_material_faltante text,
    faltou_material boolean,
    virada_rede_checklist text,
    virada_rede_concluida boolean,
    virada_rede_provas_funcionamento text
);


--
-- Name: comarcas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comarcas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comarcas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracoes_notificacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracoes_notificacao (
    id bigint NOT NULL,
    alerta_contrato_vencendo boolean NOT NULL,
    alerta_estoque_critico boolean NOT NULL,
    alerta_os_atrasada boolean NOT NULL,
    email_gestor character varying(255),
    whatsapp_gestor character varying(255)
);


--
-- Name: contratos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contratos (
    id bigint NOT NULL,
    cliente character varying(255),
    contrato character varying(255),
    escopo character varying(2000),
    valor_global numeric(19,2),
    vigencia_fim date,
    vigencia_inicio date,
    fiscal_tecnico_id bigint,
    gestor_contrato_id bigint,
    status character varying(255)
);


--
-- Name: contratos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contratos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos_assinaturas_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_assinaturas_log (
    id bigint NOT NULL,
    hash_assinatura character varying(64) NOT NULL,
    hash_documento character varying(64) NOT NULL,
    nome_assinante character varying(255) NOT NULL,
    papel character varying(40) NOT NULL,
    registrado_em timestamp(6) without time zone NOT NULL,
    registrado_por character varying(255) NOT NULL,
    documento_id bigint NOT NULL
);


--
-- Name: documentos_assinaturas_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_assinaturas_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_assinaturas_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos_internos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_internos (
    id bigint NOT NULL,
    assinatura_base64 text,
    conteudo_json text,
    criado_por character varying(255),
    data_assinatura timestamp(6) without time zone,
    data_geracao timestamp(6) without time zone,
    hash_registro character varying(128),
    recebido_por character varying(255),
    status character varying(255),
    tipo character varying(255),
    comarca_id bigint,
    assinatura_gerente_base64 text,
    assinatura_gestor_base64 text,
    assinatura_tecnico_base64 text,
    data_assinatura_gerente timestamp(6) without time zone,
    data_assinatura_gestor timestamp(6) without time zone,
    data_assinatura_tecnico timestamp(6) without time zone,
    gerente_assinado_por character varying(255),
    gestor_assinado_por character varying(255),
    tecnico_assinado_por character varying(255),
    pdf_gerado_em timestamp(6) without time zone,
    pdf_hash character varying(64),
    pdf_path character varying(255)
);


--
-- Name: documentos_internos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_internos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_internos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evidencias_foto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidencias_foto (
    id bigint NOT NULL,
    caminho_arquivo character varying(255) NOT NULL,
    data_upload timestamp(6) without time zone NOT NULL,
    latitude character varying(255),
    longitude character varying(255),
    funcionario_id bigint NOT NULL,
    ordem_servico_id bigint NOT NULL
);


--
-- Name: evidencias_foto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evidencias_foto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidencias_foto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faturamentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faturamentos (
    id bigint NOT NULL,
    data_vencimento date,
    numero_nota_fiscal character varying(255),
    servicos_executados text NOT NULL,
    situacao character varying(255) NOT NULL,
    valor_medicao numeric(38,2) NOT NULL,
    contrato_id bigint NOT NULL,
    CONSTRAINT faturamentos_situacao_check CHECK (((situacao)::text = ANY ((ARRAY['A_FATURAR'::character varying, 'FATURADO'::character varying, 'PAGO'::character varying, 'EM_ATRASO'::character varying])::text[])))
);


--
-- Name: faturamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faturamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faturamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcionario_certificacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funcionario_certificacoes (
    funcionario_id bigint NOT NULL,
    certificacao character varying(255)
);


--
-- Name: funcionario_document_paths; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funcionario_document_paths (
    funcionario_id bigint NOT NULL,
    document_path character varying(255)
);


--
-- Name: funcionarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funcionarios (
    id bigint NOT NULL,
    cidade character varying(255),
    funcao character varying(255),
    nome character varying(255)
);


--
-- Name: funcionarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.funcionarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locais_estoque; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locais_estoque (
    id bigint NOT NULL,
    ativo boolean,
    endereco character varying(255),
    nome character varying(255) NOT NULL
);


--
-- Name: locais_estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locais_estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locais_estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materiais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materiais (
    id bigint NOT NULL,
    fabricante character varying(255),
    fornecedor character varying(255),
    localizacao character varying(255),
    nome character varying(255) NOT NULL,
    part_number character varying(255) NOT NULL,
    quantidade_disponivel integer,
    quantidade_reservada integer,
    categoria character varying(255),
    descricao text,
    foto_produto_url text,
    comprimento_por_peca numeric(14,3),
    dimensao character varying(255),
    estoque_minimo numeric(14,3),
    metragem_disponivel numeric(14,3),
    tipo_controle character varying(255),
    unidade_medida character varying(255),
    metragem_reservada numeric(14,3),
    CONSTRAINT materiais_tipo_controle_check CHECK (((tipo_controle)::text = ANY ((ARRAY['UNIDADE'::character varying, 'PECA_COM_COMPRIMENTO'::character varying, 'METRAGEM'::character varying, 'ROLO'::character varying, 'BOBINA'::character varying])::text[]))),
    CONSTRAINT materiais_unidade_medida_check CHECK (((unidade_medida)::text = ANY ((ARRAY['UNIDADE'::character varying, 'PECA'::character varying, 'METRO'::character varying, 'ROLO'::character varying, 'PACOTE'::character varying, 'BOBINA'::character varying])::text[])))
);


--
-- Name: materiais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materiais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materiais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materiais_projeto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materiais_projeto (
    id bigint NOT NULL,
    quantidade_prevista integer NOT NULL,
    quantidade_utilizada integer NOT NULL,
    material_id bigint NOT NULL,
    projeto_id bigint NOT NULL
);


--
-- Name: materiais_projeto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materiais_projeto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materiais_projeto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimentacoes_estoque; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimentacoes_estoque (
    id bigint NOT NULL,
    data_movimentacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    quantidade integer,
    tipo character varying(255),
    funcionario_id bigint,
    material_id bigint,
    observacao text,
    comarca_id bigint,
    ordem_servico_id bigint,
    projeto_id bigint,
    ordem_retirada_id bigint,
    metragem numeric(14,3),
    unidade_medida character varying(255),
    unidade_rastreavel_id bigint,
    autorizado_por character varying(255),
    estoque_destino character varying(255),
    estoque_origem character varying(255),
    lancado_por character varying(255),
    motivo character varying(255),
    retirado_por character varying(255),
    saldo_anterior numeric(14,3),
    saldo_posterior numeric(14,3),
    CONSTRAINT movimentacoes_estoque_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying, 'RESERVA'::character varying, 'TRANSFERENCIA'::character varying, 'BAIXA'::character varying])::text[]))),
    CONSTRAINT movimentacoes_estoque_unidade_medida_check CHECK (((unidade_medida)::text = ANY ((ARRAY['UNIDADE'::character varying, 'PECA'::character varying, 'METRO'::character varying, 'ROLO'::character varying, 'PACOTE'::character varying, 'BOBINA'::character varying])::text[])))
);


--
-- Name: movimentacoes_estoque_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimentacoes_estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimentacoes_estoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificacoes_operacionais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificacoes_operacionais (
    id bigint NOT NULL,
    chave character varying(180) NOT NULL,
    criada_em timestamp(6) without time zone NOT NULL,
    lida_em timestamp(6) without time zone,
    mensagem character varying(2000) NOT NULL,
    severidade character varying(20) NOT NULL,
    tipo character varying(60) NOT NULL,
    titulo character varying(180) NOT NULL,
    destinatario_id bigint,
    ordem_servico_id bigint
);


--
-- Name: notificacoes_operacionais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificacoes_operacionais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_operacionais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordem_retirada_alocacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordem_retirada_alocacoes (
    id bigint NOT NULL,
    metragem_devolvida numeric(14,3) NOT NULL,
    metragem_retirada numeric(14,3) NOT NULL,
    ordem_retirada_item_id bigint NOT NULL,
    unidade_rastreavel_id bigint NOT NULL
);


--
-- Name: ordem_retirada_alocacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ordem_retirada_alocacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordem_retirada_alocacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordem_retirada_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordem_retirada_itens (
    id bigint NOT NULL,
    categoria character varying(255),
    nome_material character varying(255),
    quantidade_devolvida numeric(14,3),
    quantidade_retirada numeric(14,3),
    quantidade_solicitada numeric(14,3),
    material_id bigint,
    material_item_id bigint,
    ordem_retirada_id bigint
);


--
-- Name: ordem_retirada_itens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ordem_retirada_itens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordem_retirada_itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordens_retirada; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordens_retirada (
    id bigint NOT NULL,
    assinatura_conferente_base64 text,
    assinatura_recebimento_base64 text,
    assinatura_retirante_base64 text,
    conferido_por character varying(255),
    data_devolucao timestamp(6) without time zone,
    data_geracao timestamp(6) without time zone,
    data_retirada timestamp(6) without time zone,
    devolvido_por character varying(255),
    gerado_por character varying(255),
    levado_por character varying(255),
    numero_or character varying(255) NOT NULL,
    recebido_por character varying(255),
    status character varying(255),
    comarca_id bigint,
    ordem_servico_id bigint
);


--
-- Name: ordens_retirada_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ordens_retirada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordens_retirada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordens_servico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ordens_servico (
    id bigint NOT NULL,
    assinatura_digital text,
    checklist text,
    data_execucao date,
    descricao text,
    numero_os character varying(255) NOT NULL,
    status character varying(255),
    contrato_id bigint,
    projeto_id bigint,
    data_hora_fim timestamp(6) without time zone,
    data_hora_inicio timestamp(6) without time zone,
    deadline timestamp(6) without time zone,
    CONSTRAINT ordens_servico_status_check CHECK (((status)::text = ANY ((ARRAY['ABERTA'::character varying, 'EM_EXECUCAO'::character varying, 'AGUARDANDO_VALIDACAO'::character varying, 'CONCLUIDA'::character varying, 'FATURADA'::character varying])::text[])))
);


--
-- Name: ordens_servico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ordens_servico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordens_servico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prestacoes_contas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prestacoes_contas (
    id bigint NOT NULL,
    caminho_nota_fiscal character varying(255) NOT NULL,
    custo_real numeric(38,2) NOT NULL,
    status character varying(255) NOT NULL,
    viagem_id bigint NOT NULL
);


--
-- Name: prestacoes_contas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prestacoes_contas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prestacoes_contas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projetos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projetos (
    id bigint NOT NULL,
    data_fim date,
    data_inicio date,
    status character varying(255),
    contrato_id bigint,
    responsavel_id bigint,
    as_built_status character varying(255),
    CONSTRAINT projetos_status_check CHECK (((status)::text = ANY ((ARRAY['PLANEJAMENTO'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying, 'SUSPENSO'::character varying, 'CANCELADO'::character varying])::text[])))
);


--
-- Name: projetos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projetos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projetos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registros_ponto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_ponto (
    id bigint NOT NULL,
    data_hora timestamp(6) without time zone NOT NULL,
    latitude character varying(255),
    longitude character varying(255),
    tipo character varying(255) NOT NULL,
    funcionario_id bigint NOT NULL,
    CONSTRAINT registros_ponto_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


--
-- Name: registros_ponto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registros_ponto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registros_ponto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saldos_materiais_locais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saldos_materiais_locais (
    id bigint NOT NULL,
    metragem_disponivel numeric(14,3) NOT NULL,
    metragem_reservada numeric(14,3) NOT NULL,
    quantidade_disponivel integer,
    quantidade_reservada integer,
    local_estoque_id bigint NOT NULL,
    material_id bigint NOT NULL
);


--
-- Name: saldos_materiais_locais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saldos_materiais_locais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saldos_materiais_locais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidades_estoque_rastreaveis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unidades_estoque_rastreaveis (
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    data_entrada timestamp(6) without time zone NOT NULL,
    metragem_atual numeric(14,3) NOT NULL,
    metragem_inicial numeric(14,3) NOT NULL,
    observacao text,
    status character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    material_id bigint NOT NULL,
    local_estoque_id bigint,
    CONSTRAINT unidades_estoque_rastreaveis_status_check CHECK (((status)::text = ANY ((ARRAY['LACRADA'::character varying, 'EM_USO'::character varying, 'PARCIALMENTE_UTILIZADA'::character varying, 'ESGOTADA'::character varying, 'DEVOLVIDA_ESTOQUE'::character varying])::text[]))),
    CONSTRAINT unidades_estoque_rastreaveis_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['UNIDADE'::character varying, 'PECA_COM_COMPRIMENTO'::character varying, 'METRAGEM'::character varying, 'ROLO'::character varying, 'BOBINA'::character varying])::text[])))
);


--
-- Name: unidades_estoque_rastreaveis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unidades_estoque_rastreaveis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidades_estoque_rastreaveis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viagens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.viagens (
    id bigint NOT NULL,
    adiantamento_diarias numeric(38,2),
    custo_planejado numeric(38,2),
    hospedagem_detalhes character varying(255),
    solicitacao_veiculo character varying(255),
    status character varying(255) NOT NULL,
    funcionario_id bigint NOT NULL,
    projeto_id bigint NOT NULL,
    CONSTRAINT viagens_status_check CHECK (((status)::text = ANY ((ARRAY['PLANEJADA'::character varying, 'EM_ANDAMENTO'::character varying, 'AGUARDANDO_CONTAS'::character varying, 'CONCLUIDA'::character varying])::text[])))
);


--
-- Name: viagens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.viagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: as_builts as_builts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_builts
    ADD CONSTRAINT as_builts_pkey PRIMARY KEY (id);


--
-- Name: atividades_comarca atividades_comarca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.atividades_comarca
    ADD CONSTRAINT atividades_comarca_pkey PRIMARY KEY (id);


--
-- Name: atividades_padrao atividades_padrao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.atividades_padrao
    ADD CONSTRAINT atividades_padrao_pkey PRIMARY KEY (id);


--
-- Name: comarca_materiais comarca_materiais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarca_materiais
    ADD CONSTRAINT comarca_materiais_pkey PRIMARY KEY (id);


--
-- Name: comarcas comarcas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarcas
    ADD CONSTRAINT comarcas_pkey PRIMARY KEY (id);


--
-- Name: configuracoes_notificacao configuracoes_notificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracoes_notificacao
    ADD CONSTRAINT configuracoes_notificacao_pkey PRIMARY KEY (id);


--
-- Name: contratos contratos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_pkey PRIMARY KEY (id);


--
-- Name: documentos_assinaturas_log documentos_assinaturas_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_assinaturas_log
    ADD CONSTRAINT documentos_assinaturas_log_pkey PRIMARY KEY (id);


--
-- Name: documentos_internos documentos_internos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_internos
    ADD CONSTRAINT documentos_internos_pkey PRIMARY KEY (id);


--
-- Name: evidencias_foto evidencias_foto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidencias_foto
    ADD CONSTRAINT evidencias_foto_pkey PRIMARY KEY (id);


--
-- Name: faturamentos faturamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faturamentos
    ADD CONSTRAINT faturamentos_pkey PRIMARY KEY (id);


--
-- Name: funcionarios funcionarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionarios
    ADD CONSTRAINT funcionarios_pkey PRIMARY KEY (id);


--
-- Name: locais_estoque locais_estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locais_estoque
    ADD CONSTRAINT locais_estoque_pkey PRIMARY KEY (id);


--
-- Name: materiais materiais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materiais
    ADD CONSTRAINT materiais_pkey PRIMARY KEY (id);


--
-- Name: materiais_projeto materiais_projeto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materiais_projeto
    ADD CONSTRAINT materiais_projeto_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes_estoque movimentacoes_estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT movimentacoes_estoque_pkey PRIMARY KEY (id);


--
-- Name: notificacoes_operacionais notificacoes_operacionais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes_operacionais
    ADD CONSTRAINT notificacoes_operacionais_pkey PRIMARY KEY (id);


--
-- Name: ordem_retirada_alocacoes ordem_retirada_alocacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_alocacoes
    ADD CONSTRAINT ordem_retirada_alocacoes_pkey PRIMARY KEY (id);


--
-- Name: ordem_retirada_itens ordem_retirada_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_itens
    ADD CONSTRAINT ordem_retirada_itens_pkey PRIMARY KEY (id);


--
-- Name: ordens_retirada ordens_retirada_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_retirada
    ADD CONSTRAINT ordens_retirada_pkey PRIMARY KEY (id);


--
-- Name: ordens_servico ordens_servico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT ordens_servico_pkey PRIMARY KEY (id);


--
-- Name: prestacoes_contas prestacoes_contas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prestacoes_contas
    ADD CONSTRAINT prestacoes_contas_pkey PRIMARY KEY (id);


--
-- Name: projetos projetos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT projetos_pkey PRIMARY KEY (id);


--
-- Name: registros_ponto registros_ponto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_ponto
    ADD CONSTRAINT registros_ponto_pkey PRIMARY KEY (id);


--
-- Name: saldos_materiais_locais saldos_materiais_locais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldos_materiais_locais
    ADD CONSTRAINT saldos_materiais_locais_pkey PRIMARY KEY (id);


--
-- Name: unidades_estoque_rastreaveis uk2hwcqbehqi7w6flwujw4m2l08; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades_estoque_rastreaveis
    ADD CONSTRAINT uk2hwcqbehqi7w6flwujw4m2l08 UNIQUE (codigo);


--
-- Name: ordens_servico uk38vkgxu47h79on0qts60pty05; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT uk38vkgxu47h79on0qts60pty05 UNIQUE (numero_os);


--
-- Name: saldos_materiais_locais uk6ph6n3m75h6b7rw6oi3bbfmh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldos_materiais_locais
    ADD CONSTRAINT uk6ph6n3m75h6b7rw6oi3bbfmh UNIQUE (material_id, local_estoque_id);


--
-- Name: locais_estoque uk8xy2xgqyshnhyufqa2esy4kr8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locais_estoque
    ADD CONSTRAINT uk8xy2xgqyshnhyufqa2esy4kr8 UNIQUE (nome);


--
-- Name: prestacoes_contas uk9jtlllpxkr3kdinrgwgp6qi5s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prestacoes_contas
    ADD CONSTRAINT uk9jtlllpxkr3kdinrgwgp6qi5s UNIQUE (viagem_id);


--
-- Name: notificacoes_operacionais uk_notificacao_chave; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes_operacionais
    ADD CONSTRAINT uk_notificacao_chave UNIQUE (chave);


--
-- Name: comarcas ukaib4byapva6uibgvj3338h5y1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarcas
    ADD CONSTRAINT ukaib4byapva6uibgvj3338h5y1 UNIQUE (ordem_servico_id);


--
-- Name: ordens_retirada ukao5p4t7ngvhb9ix1037hv7565; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_retirada
    ADD CONSTRAINT ukao5p4t7ngvhb9ix1037hv7565 UNIQUE (numero_or);


--
-- Name: materiais ukjnribs1jnmg8gch5rh05o3tvt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materiais
    ADD CONSTRAINT ukjnribs1jnmg8gch5rh05o3tvt UNIQUE (part_number);


--
-- Name: unidades_estoque_rastreaveis unidades_estoque_rastreaveis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades_estoque_rastreaveis
    ADD CONSTRAINT unidades_estoque_rastreaveis_pkey PRIMARY KEY (id);


--
-- Name: viagens viagens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viagens
    ADD CONSTRAINT viagens_pkey PRIMARY KEY (id);


--
-- Name: ordem_retirada_alocacoes fk1ae6d35n95ocho0x9bqco5ygx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_alocacoes
    ADD CONSTRAINT fk1ae6d35n95ocho0x9bqco5ygx FOREIGN KEY (ordem_retirada_item_id) REFERENCES public.ordem_retirada_itens(id);


--
-- Name: viagens fk2081pnyl842vgup1bsdyxhu9c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viagens
    ADD CONSTRAINT fk2081pnyl842vgup1bsdyxhu9c FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: materiais_projeto fk20tfcpd3p5oyxuxu8qyhle6qu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materiais_projeto
    ADD CONSTRAINT fk20tfcpd3p5oyxuxu8qyhle6qu FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: unidades_estoque_rastreaveis fk2dnw735giwnqqplcmqylfdaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades_estoque_rastreaveis
    ADD CONSTRAINT fk2dnw735giwnqqplcmqylfdaq FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: movimentacoes_estoque fk2ulmhhmplv0q5g7ahynjo3suc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fk2ulmhhmplv0q5g7ahynjo3suc FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: documentos_internos fk347sokd2t2nuikan10192jyrk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_internos
    ADD CONSTRAINT fk347sokd2t2nuikan10192jyrk FOREIGN KEY (comarca_id) REFERENCES public.comarcas(id);


--
-- Name: funcionario_document_paths fk443lcwcsmvv1mt3o7w4we1tkj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionario_document_paths
    ADD CONSTRAINT fk443lcwcsmvv1mt3o7w4we1tkj FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: ordens_retirada fk4tvjaxkdg6d7svw8wmcda6vhe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_retirada
    ADD CONSTRAINT fk4tvjaxkdg6d7svw8wmcda6vhe FOREIGN KEY (comarca_id) REFERENCES public.comarcas(id);


--
-- Name: funcionario_certificacoes fk5gam1dn8ck67f9boptwv9hb4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funcionario_certificacoes
    ADD CONSTRAINT fk5gam1dn8ck67f9boptwv9hb4t FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: movimentacoes_estoque fk87o0jkit6ewsx313gddnvfxct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fk87o0jkit6ewsx313gddnvfxct FOREIGN KEY (unidade_rastreavel_id) REFERENCES public.unidades_estoque_rastreaveis(id);


--
-- Name: notificacoes_operacionais fk8s7mn0yqvg1mnlvji57qm59hi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes_operacionais
    ADD CONSTRAINT fk8s7mn0yqvg1mnlvji57qm59hi FOREIGN KEY (destinatario_id) REFERENCES public.funcionarios(id);


--
-- Name: ordens_retirada fkadpphjq313i8ig5ryp4b5ws2l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_retirada
    ADD CONSTRAINT fkadpphjq313i8ig5ryp4b5ws2l FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id);


--
-- Name: registros_ponto fkbba504le6nr2287pxnw9j1xna; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_ponto
    ADD CONSTRAINT fkbba504le6nr2287pxnw9j1xna FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: evidencias_foto fkbdkmptk6osfqm3p3o69fnyxec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidencias_foto
    ADD CONSTRAINT fkbdkmptk6osfqm3p3o69fnyxec FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id);


--
-- Name: movimentacoes_estoque fkckm5l353gaqbweljevh12c3mq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkckm5l353gaqbweljevh12c3mq FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: atividades_comarca fkf15nobprd4r8ygn44ijndq1ba; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.atividades_comarca
    ADD CONSTRAINT fkf15nobprd4r8ygn44ijndq1ba FOREIGN KEY (comarca_id) REFERENCES public.comarcas(id);


--
-- Name: as_builts fkfdd41b1jpysh0us4ggvu79uf2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_builts
    ADD CONSTRAINT fkfdd41b1jpysh0us4ggvu79uf2 FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: contratos fkfsc2ray4dd0isupb9ku3ltlu1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT fkfsc2ray4dd0isupb9ku3ltlu1 FOREIGN KEY (fiscal_tecnico_id) REFERENCES public.funcionarios(id);


--
-- Name: movimentacoes_estoque fkg4m3yjee2w5hc9yqt0s60n5i6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkg4m3yjee2w5hc9yqt0s60n5i6 FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id);


--
-- Name: faturamentos fkg9nm0lecmtpm8qx60alxoulv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faturamentos
    ADD CONSTRAINT fkg9nm0lecmtpm8qx60alxoulv FOREIGN KEY (contrato_id) REFERENCES public.contratos(id);


--
-- Name: ordem_retirada_itens fkgm2fpcxpkjvrp8ia8382kus3b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_itens
    ADD CONSTRAINT fkgm2fpcxpkjvrp8ia8382kus3b FOREIGN KEY (material_item_id) REFERENCES public.comarca_materiais(id);


--
-- Name: atividade_comarca_fotos fkgwfn5l4csg5savldn79ytmm9h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.atividade_comarca_fotos
    ADD CONSTRAINT fkgwfn5l4csg5savldn79ytmm9h FOREIGN KEY (atividade_comarca_id) REFERENCES public.atividades_comarca(id);


--
-- Name: materiais_projeto fkh2lpa45ugx9ewknhgm4g80yvh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materiais_projeto
    ADD CONSTRAINT fkh2lpa45ugx9ewknhgm4g80yvh FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: projetos fkhggl4eag8cernxaaxpqtcsp31; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT fkhggl4eag8cernxaaxpqtcsp31 FOREIGN KEY (responsavel_id) REFERENCES public.funcionarios(id);


--
-- Name: contratos fkhqw2cbka15u9ikb38fsb4nfrm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT fkhqw2cbka15u9ikb38fsb4nfrm FOREIGN KEY (gestor_contrato_id) REFERENCES public.funcionarios(id);


--
-- Name: comarca_materiais fkikwvqu59qnq589g3uen84d821; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarca_materiais
    ADD CONSTRAINT fkikwvqu59qnq589g3uen84d821 FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: ordem_retirada_itens fkioys4el1txe5lm18kk31t94m5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_itens
    ADD CONSTRAINT fkioys4el1txe5lm18kk31t94m5 FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: saldos_materiais_locais fkjkv3t4fa1l1069kg3ko7abpfl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldos_materiais_locais
    ADD CONSTRAINT fkjkv3t4fa1l1069kg3ko7abpfl FOREIGN KEY (material_id) REFERENCES public.materiais(id);


--
-- Name: prestacoes_contas fkjvxt0k3t5jclyypw207lf6xmb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prestacoes_contas
    ADD CONSTRAINT fkjvxt0k3t5jclyypw207lf6xmb FOREIGN KEY (viagem_id) REFERENCES public.viagens(id);


--
-- Name: movimentacoes_estoque fkk1ivv6ow7l16rpmwkuk3d3fua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkk1ivv6ow7l16rpmwkuk3d3fua FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: saldos_materiais_locais fkk3ttyjs0ix61kbvjfea7yflf6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saldos_materiais_locais
    ADD CONSTRAINT fkk3ttyjs0ix61kbvjfea7yflf6 FOREIGN KEY (local_estoque_id) REFERENCES public.locais_estoque(id);


--
-- Name: comarca_materiais fkk4dk3093358wn9ubp2f3td1k7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarca_materiais
    ADD CONSTRAINT fkk4dk3093358wn9ubp2f3td1k7 FOREIGN KEY (comarca_id) REFERENCES public.comarcas(id);


--
-- Name: ordens_servico fkkn3tyemqa5hxl6dyi5ggf5utl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT fkkn3tyemqa5hxl6dyi5ggf5utl FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: movimentacoes_estoque fkl0psbmv4q51vnywygftnsknpl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkl0psbmv4q51vnywygftnsknpl FOREIGN KEY (comarca_id) REFERENCES public.comarcas(id);


--
-- Name: documentos_assinaturas_log fkl4mipih2q06fbvqn7inosgkek; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_assinaturas_log
    ADD CONSTRAINT fkl4mipih2q06fbvqn7inosgkek FOREIGN KEY (documento_id) REFERENCES public.documentos_internos(id);


--
-- Name: comarcas fkld2j6gt5f7vs9wlp32a2yk24p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarcas
    ADD CONSTRAINT fkld2j6gt5f7vs9wlp32a2yk24p FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id);


--
-- Name: projetos fkm6nvcy3a8ic2f060k1qal0qjj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT fkm6nvcy3a8ic2f060k1qal0qjj FOREIGN KEY (contrato_id) REFERENCES public.contratos(id);


--
-- Name: comarcas fkmct2c0ivaqmft24r7d4a3js06; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comarcas
    ADD CONSTRAINT fkmct2c0ivaqmft24r7d4a3js06 FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: unidades_estoque_rastreaveis fkn35nqnfhbvolou78dp30cwypd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unidades_estoque_rastreaveis
    ADD CONSTRAINT fkn35nqnfhbvolou78dp30cwypd FOREIGN KEY (local_estoque_id) REFERENCES public.locais_estoque(id);


--
-- Name: evidencias_foto fkna7av1ny7qho7wqse34h6u7qv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidencias_foto
    ADD CONSTRAINT fkna7av1ny7qho7wqse34h6u7qv FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: ordem_retirada_itens fkodp8d6o98po0vtmi3msguiss8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_itens
    ADD CONSTRAINT fkodp8d6o98po0vtmi3msguiss8 FOREIGN KEY (ordem_retirada_id) REFERENCES public.ordens_retirada(id);


--
-- Name: movimentacoes_estoque fkojuleenx7geej6srs45hfm99p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_estoque
    ADD CONSTRAINT fkojuleenx7geej6srs45hfm99p FOREIGN KEY (ordem_retirada_id) REFERENCES public.ordens_retirada(id);


--
-- Name: ordem_retirada_alocacoes fkql7xbh4jhegpkf3kraf6jmkcu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordem_retirada_alocacoes
    ADD CONSTRAINT fkql7xbh4jhegpkf3kraf6jmkcu FOREIGN KEY (unidade_rastreavel_id) REFERENCES public.unidades_estoque_rastreaveis(id);


--
-- Name: notificacoes_operacionais fkrbgbg1kxb3d50ce6f2gmrde1m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes_operacionais
    ADD CONSTRAINT fkrbgbg1kxb3d50ce6f2gmrde1m FOREIGN KEY (ordem_servico_id) REFERENCES public.ordens_servico(id);


--
-- Name: viagens fkrwxen3g3lnqhujbc1gh4r14cd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.viagens
    ADD CONSTRAINT fkrwxen3g3lnqhujbc1gh4r14cd FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id);


--
-- Name: ordens_servico fks4scxguk5balahimeda48a2dm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ordens_servico
    ADD CONSTRAINT fks4scxguk5balahimeda48a2dm FOREIGN KEY (contrato_id) REFERENCES public.contratos(id);


--
-- PostgreSQL database dump complete
--
