CREATE TABLE ordens_retirada_documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_retirada_id BIGINT NOT NULL,
    fase VARCHAR(24) NOT NULL,
    status_or VARCHAR(24) NOT NULL,
    pdf_path VARCHAR(512) NOT NULL,
    pdf_hash VARCHAR(64) NOT NULL,
    gerado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_or_documento_ordem
        FOREIGN KEY (ordem_retirada_id) REFERENCES ordens_retirada(id),
    CONSTRAINT uk_or_documento_fase
        UNIQUE (ordem_retirada_id, fase)
);

CREATE INDEX idx_or_documentos_ordem_data
    ON ordens_retirada_documentos (ordem_retirada_id, gerado_em);

CREATE OR REPLACE FUNCTION bloquear_alteracao_documento_or()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'ordens_retirada_documentos e append-only: UPDATE e DELETE nao sao permitidos';
END;
$$;

CREATE TRIGGER trg_ordens_retirada_documentos_append_only
BEFORE UPDATE OR DELETE ON ordens_retirada_documentos
FOR EACH ROW
EXECUTE FUNCTION bloquear_alteracao_documento_or();
