ALTER TABLE materiais
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE saldos_materiais_locais
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE unidades_estoque_rastreaveis
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ordens_retirada
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
