export const PERMISSOES = Object.freeze({
  DASHBOARD_VISUALIZAR: "dashboard.visualizar",
  CONTRATOS_VISUALIZAR: "contratos.visualizar",
  PROJETOS_VISUALIZAR: "projetos.visualizar",
  FUNCIONARIOS_VISUALIZAR: "funcionarios.visualizar",
  FUNCIONARIOS_GERENCIAR: "funcionarios.gerenciar",
  OS_VISUALIZAR: "os.visualizar",
  OS_GERENCIAR: "os.gerenciar",
  OBRAS_VISUALIZAR: "obras.visualizar",
  OBRAS_EXECUTAR: "obras.executar",
  OBRAS_GERENCIAR: "obras.gerenciar",
  ESTOQUE_VISUALIZAR: "estoque.visualizar",
  AUDITORIA_VISUALIZAR: "auditoria.visualizar",
  FINANCEIRO_VISUALIZAR: "financeiro.visualizar",
  NOTIFICACOES_VISUALIZAR: "notificacoes.visualizar",
  ATIVIDADES_GERENCIAR: "atividades.gerenciar",
  PORTAL_TECNICO_VISUALIZAR: "portal-tecnico.visualizar",
  OR_GERENCIAR: "ordem-retirada.gerenciar",
  DOCUMENTOS_EDITAR: "documentos.editar",
});

const PERFIS_POR_PERMISSAO = Object.freeze({
  [PERMISSOES.DASHBOARD_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.CONTRATOS_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.PROJETOS_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.FUNCIONARIOS_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO", "ESTOQUE"],
  [PERMISSOES.FUNCIONARIOS_GERENCIAR]: ["ADMIN"],
  [PERMISSOES.OS_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO", "TECNICO"],
  [PERMISSOES.OS_GERENCIAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.OBRAS_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO", "TECNICO", "AUDITOR"],
  [PERMISSOES.OBRAS_EXECUTAR]: ["ADMIN", "SUPERVISOR_TECNICO", "TECNICO"],
  [PERMISSOES.OBRAS_GERENCIAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.ESTOQUE_VISUALIZAR]: ["ADMIN", "ESTOQUE"],
  [PERMISSOES.AUDITORIA_VISUALIZAR]: ["ADMIN", "AUDITOR"],
  [PERMISSOES.FINANCEIRO_VISUALIZAR]: ["ADMIN"],
  [PERMISSOES.NOTIFICACOES_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO"],
  [PERMISSOES.ATIVIDADES_GERENCIAR]: ["ADMIN"],
  [PERMISSOES.PORTAL_TECNICO_VISUALIZAR]: ["ADMIN", "SUPERVISOR_TECNICO", "TECNICO"],
  [PERMISSOES.OR_GERENCIAR]: ["ADMIN", "ESTOQUE"],
  [PERMISSOES.DOCUMENTOS_EDITAR]: ["ADMIN", "SUPERVISOR_TECNICO", "TECNICO"],
});

export function perfisComPermissao(permissao) {
  return PERFIS_POR_PERMISSAO[permissao] || [];
}

export function temPermissao(perfil, permissao) {
  return Boolean(perfil && perfisComPermissao(permissao).includes(perfil));
}
